/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface ChuckNorrisJokes {
      'firstname': string;
      'lastname': string;
    }
  }


    interface HTMLChuckNorrisJokesElement extends StencilComponents.ChuckNorrisJokes, HTMLStencilElement {}

    var HTMLChuckNorrisJokesElement: {
      prototype: HTMLChuckNorrisJokesElement;
      new (): HTMLChuckNorrisJokesElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'chuck-norris-jokes': JSXElements.ChuckNorrisJokesAttributes;
    }
  }

  namespace JSXElements {

    export interface ChuckNorrisJokesAttributes extends HTMLAttributes {
      'firstname'?: string;
      'lastname'?: string;
    }
  }

  interface HTMLElementTagNameMap {
    'chuck-norris-jokes': HTMLChuckNorrisJokesElement
  }

  interface ElementTagNameMap {
    'chuck-norris-jokes': HTMLChuckNorrisJokesElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;