/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ChuckNorrisJokes {
    'firstname': string;
    'lastname': string;
  }
}

declare global {


  interface HTMLChuckNorrisJokesElement extends Components.ChuckNorrisJokes, HTMLStencilElement {}
  var HTMLChuckNorrisJokesElement: {
    prototype: HTMLChuckNorrisJokesElement;
    new (): HTMLChuckNorrisJokesElement;
  };
  interface HTMLElementTagNameMap {
    'chuck-norris-jokes': HTMLChuckNorrisJokesElement;
  }
}

declare namespace LocalJSX {
  interface ChuckNorrisJokes {
    'firstname'?: string;
    'lastname'?: string;
  }

  interface IntrinsicElements {
    'chuck-norris-jokes': ChuckNorrisJokes;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'chuck-norris-jokes': LocalJSX.ChuckNorrisJokes & JSXBase.HTMLAttributes<HTMLChuckNorrisJokesElement>;
    }
  }
}


